#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Using Earth Observation for Journalism  # The title of the book. Will be placed in the left navbar.
author: Arne Schlüter  # The author of the book
copyright: "CC-BY-SA 4.0. Header image: \"Herschel's 40-foot telescope\" (public domain)"  # Copyright year to be placed in the footer
logo: great-forty-foot-telescope-wikipedia.png  # A path to the book logo
execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/heyarne/earth-observation-for-journalism
html:
  use_repository_button: true
  
parse:
  # defaults are extended to include amsmath
  # see https://jupyterbook.org/customize/config.html?highlight=default#configuration-defaults
  myst_enable_extensions:
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
 
exclude_patterns: [_build, .cache, .config, .local, .npm, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
