#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Remote Sensing for Journalism  # The title of the book. Will be placed in the left navbar.
author: Arne Schlüter  # The author of the book
copyright: "CC-BY-SA 4.0 2021"  # Copyright year to be placed in the footer
logo: great-forty-foot-telescope-wikipedia.png  # A path to the book logo
execute:
  execute_notebooks: "off"
